=== GourabIX/Java_FSD/Assignment/xml/MovieXMLProject/bin/movies.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT movie-info (movie+)>
<!ELEMENT movie (id, title, release-date, theatre+)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT release-date (day, month, year)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT theatre (#PCDATA)>

=== GourabIX/Java_FSD/Assignment/xml/MovieXMLProject/src/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movie-info SYSTEM "movies.dtd" >
<movie-info>
  <movie>
    <id>101</id>
    <title>"Harry Potter and the Order of the Phoenix</title>
    <release-date>
      <day>24</day>
      <month>September</month>
      <year>2006</year>
    </release-date>
    <theatre>IMAX Quest Mall</theatre>
  </movie>
  
   <movie>
    <id>102</id>
    <title>JOKER</title>
    <release-date>
      <day>04</day>
      <month>October</month>
      <year>2019</year>
    </release-date>
    <theatre>IMAX Quest Mall</theatre>
  </movie>
  
     <movie>
    <id>103</id>
    <title>The Chronicles of Charan's thika</title>
    <release-date>
      <day>06</day>
      <month>October</month>
      <year>2019</year>
    </release-date>
    <theatre>IMAX Quest Mall</theatre>
  </movie>
</movie-info>
